apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-server
  labels:
    app: cinema-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-server
  template:
    metadata:
      labels:
        app: cinema-server
    spec:
      containers:
      - name: cinema-server
        image: thayanan/cinema-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: uri
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-client
  labels:
    app: cinema-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-client
  template:
    metadata:
      labels:
        app: cinema-client
    spec:
      containers:
      - name: cinema-client
        image: thayanan/cinema-client:latest
        ports:
        - containerPort: 3000
