apiVersion: v1
kind: Service
metadata:
  name: cinema-server
spec:
  selector:
    app: cinema-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cinema-client
spec:
  selector:
    app: cinema-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
