apiVersion: v1
kind: Service
metadata:
  name: cinema-server
  namespace: default
spec:
  selector:
    app: cinema-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: cinema-client
  namespace: default
spec:
  selector:
    app: cinema-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
